spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-zhshero-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-zhshero-test    